---
title: "Stats_desc_politique"
format: html
editor: visual
---

```{r}
library(haven)
library(tidyverse)
library(ggthemes)
library(wesanderson)
library(stringr)
```

```{r}
theme_set(theme_clean() + theme(axis.line.y.right=element_line(color="red"),
        axis.text.y.right=element_text(color="red"),
        axis.title.y.right=element_text(color="red", angle=90),
        axis.title.y.left=element_text(angle=90),
        plot.caption=element_text(hjust=0, size=9.5),
        plot.caption.position = "plot"))
palette=wes_palette("Chevalier1", n=4)
```

```{r}
base <- read_dta("LYCEES_base.dta")

# Transformation des variables labellisées en facteurs si nécessaire
base <- base %>% mutate_if(is.labelled, as_factor)
```

On regarde un peu les opinions politiques professées

```{r}
ggplot(base, aes(x = as.factor(q27a))) +
  geom_bar(fill = "blue", color = "black") +
  labs(title = "Opinion politique du répondant", x = "Réponse", y = "Fréquence") +
  theme_minimal()

round(prop.table(table(base$q27a, useNA = "ifany")) * 100, 1)

ggplot(base, aes(x = as.factor(q27b))) +
  geom_bar(fill = "blue", color = "black") +
  labs(title = "Opinion politique du père", x = "Réponse", y = "Fréquence") +
  theme_minimal()

round(prop.table(table(base$q27b, useNA = "ifany")) * 100, 1)

ggplot(base, aes(x = as.factor(q27c))) +
  geom_bar(fill = "blue", color = "black") +
  labs(title = "Opinion politique de la mère", x = "Réponse", y = "Fréquence") +
  theme_minimal()

round(prop.table(table(base$q27b, useNA = "ifany")) * 100, 1)
```

Cela semble quand même pas mal décallé vers la gauche, ce qui est étrange... Bon, prédominance aussi des NA.

On essaie de voir ce que cela donne avec de la pondération.

```{r}
ggplot(base, aes(x = as.factor(q27a), weight = pond)) +
  geom_bar(fill = "blue", color = "black") +
  labs(title = "Opinion politique du répondant (avec pondération)", x = "Réponse", y = "Fréquence") +
  theme_minimal()

ggplot(base, aes(x = as.factor(q27b), weight = pond)) +
  geom_bar(fill = "blue", color = "black") +
  labs(title = "Opinion politique du père (avec pondération)", x = "Réponse", y = "Fréquence") +
  theme_minimal()

ggplot(base, aes(x = as.factor(q27c), weight = pond)) +
  geom_bar(fill = "blue", color = "black") +
  labs(title = "Opinion politique de la mère (avec pondération)", x = "Réponse", y = "Fréquence") +
  theme_minimal()
```

De fait, on retrouve un peu la même chose, il ne semble pas que cela change fondamentalement le problème.

```{r}
modalites <- c(
  "Pas du tout d'accord" = 1,
  "Pas d'accord" = 2,
  "Ni d'accord, ni pas d'accord" = 3,
  "D'accord" = 4,
  "Tout à fait d'accord" = 5
)

labels_list_accord <- c(
  "Je suis intéressé par la politique",
  "Lorsque des sujets politiques sont débattus, j'ai la plupart du temps quelque chose à dire",
  "J'ai des opinions politiques qu'il serait intéressant d'écouter",
  "Je parle souvent de politique avec mes parents",
  "Je parle souvent de politique aves mes ami.es",
  "Lorsque je rencontre des difficultés pour faire mes devoirs, je demande de l'aide à mes parents"
)

Accord_affirmations_q26 <- base %>%
  select(q26a, q26b, q26c, q26d, q26e, q26f) %>%
  mutate(across(everything(), ~ modalites[.])) %>%
  pivot_longer(cols = everything(), names_to = "Variable", values_to = "Accord") %>%
  group_by(Variable) %>%
  summarise(accord_moyen=mean(Accord, na.rm=TRUE),
            accord_ET=sd(Accord, na.rm=TRUE)) %>%
  mutate(question=labels_list_accord)

ggplot(Accord_affirmations_q26) +
  geom_point(aes(x=question, y=accord_moyen)) +
  geom_errorbar(aes(x=question, ymin = accord_moyen - accord_ET, ymax = accord_moyen + accord_ET), width = 0.2) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 14)) +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5))
```

```{r}
df_proportions_gauche_droite <- base %>%
  select(q27a, q27b, q27c) %>%  
  pivot_longer(everything(), names_to = "Question", values_to = "Réponse") %>%
  group_by(Question, Réponse) %>%
  summarise(count = n() , .groups = "drop") %>%
  ungroup() %>%
  group_by(Question) %>%
  mutate(proportion=round(count/sum(count),4)*100) %>%
  mutate(individu=case_when(
    Question=="q27a" ~ "lycéen",
    Question=="q27b" ~ "père",
    Question=="q27c" ~ "mère",
  )) %>%
  ungroup() %>%
  group_by(Réponse)

ggplot(df_proportions_gauche_droite, aes(x=Réponse, y=proportion, fill=individu)) +
  geom_col(position = "dodge") +
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5)) +
  scale_fill_manual(values=palette)
```

```{r}
proportions_qualificatifs <- base %>%
  select(starts_with("q30")) %>%
  select(-q30s_com)
labels_list <- sapply(proportions_qualificatifs, function(x) attr(x, "label"))
labels_last_word <- sub(".*\\s+", "", labels_list)
labels_last_word[18] <- "Rien de tout ça"

proportions_qualificatifs=proportions_qualificatifs %>%
  mutate(across(everything(), as.character)) %>%
  summarise(across(everything(), ~ round(sum(. == "Oui", na.rm=TRUE)/n(), 4)*100))
colnames(proportions_qualificatifs)=labels_last_word

proportions_qualificatifs=proportions_qualificatifs %>%
  pivot_longer(cols=colnames(.),
               names_to = "Qualificatif",
               values_to = "Prévalence") %>%
  arrange(desc(Prévalence))

ggplot(data = proportions_qualificatifs, aes(x=fct_reorder(Qualificatif, Prévalence, .desc=TRUE), y=Prévalence)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  labs(x="Qualificatif", y="Prévalence (%)")
```
